home:
  path: /
  controller: App\Controller\HomeController::index

logout:
  path: /logout
  controller: App\Controller\SecurityController
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
